// @author cooper15
 
package presentacion;

import java.awt.event.MouseEvent;
import negocio.NegocioInventario;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;

public class ContenedorInventario extends javax.swing.JPanel 
{   
    java.awt.Frame parent;
    /*Creates new form ContenedorInventario*/
    public ContenedorInventario(java.awt.Frame parent) 
    {   
        this.parent = parent;
        initComponents();
        cargarInventario();
        
        // Deshabilitamos los botones innecesarios para actualizar, eliminar, descontar
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnDescontar.setEnabled(false);
        
        setEventoMouseClicked();
    }// fin del constructor de ContenedorInventario

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTablaInventario = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnDescontar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        pnlTablaInventario.setBorder(javax.swing.BorderFactory.createTitledBorder("Existencias"));
        pnlTablaInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTablaInventarioMouseClicked(evt);
            }
        });

        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Cantidad", "Tamaño", "Tipo"
            }
        ));
        jScrollPane2.setViewportView(tblInventario);

        javax.swing.GroupLayout pnlTablaInventarioLayout = new javax.swing.GroupLayout(pnlTablaInventario);
        pnlTablaInventario.setLayout(pnlTablaInventarioLayout);
        pnlTablaInventarioLayout.setHorizontalGroup(
            pnlTablaInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTablaInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTablaInventarioLayout.setVerticalGroup(
            pnlTablaInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTablaInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");

        btnDescontar.setText("Descontar");

        btnActualizar.setText("Actualizar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnDescontar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregar)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDescontar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addComponent(btnActualizar)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlTablaInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTablaInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        AgregarInventario nuevoAgregar = new AgregarInventario(this.parent,true);
        nuevoAgregar.setVisible(true);
        cargarInventario();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void pnlTablaInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTablaInventarioMouseClicked
       
        btnAgregar.setEnabled(true);
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnDescontar.setEnabled(false);
    }//GEN-LAST:event_pnlTablaInventarioMouseClicked
    
    public void cargarInventario()
    {
        NegocioInventario objNegocioInventario = new NegocioInventario();
        ResultSet rs;
        
        DefaultTableModel modelo = new DefaultTableModel();
        String cabezera [] = {"Nombre", "Cantidad", "Tamaño", "Vía de Administración"};
        String fila [] = new String [cabezera.length];  // fila con 4 campos en este caso
        
        for (int i = 0; i < cabezera.length; i++)  // recorremos cabezera y vamos insertando cada elemento
            modelo.addColumn(cabezera [i]);            // de cabezera como una columna
         
        try
        {
            rs = objNegocioInventario.listarInventario();
            
            while(rs.next())
            {
                for (int i = 0; i < fila.length; i++)
                    fila [i] = rs.getString(i + 1);
                
                modelo.addRow(fila);  // insertamos la fila en el modelo de la tabla
            }// fin del whiele
            
            tblInventario.setModel(modelo);
            rs.close();
        }// fin del try
        catch(SQLException sqle)
        {
            System.out.println(sqle.getErrorCode() + sqle.getMessage());
        }// fin del catch
                
    }// fin del metodo cargarInventario
    
    // Este metodo llama al metodo que habilita los botones al clickear un elemento de la tabla
    private void setEventoMouseClicked()
    {
        tblInventario.addMouseListener(new java.awt.event.MouseAdapter()
            {
                @Override
                public void mouseClicked(MouseEvent e) 
                {
                    clickEnRegistro(e);
                }
            }// fin de la clase interna anonima
        );
    }// fin del metodo setEventoMouseClicked
    
    private void clickEnRegistro(MouseEvent evt)
    {
        int row = tblInventario.rowAtPoint(evt.getPoint());
        
        if (row >= 0)
        {
            btnAgregar.setEnabled(false);
            btnActualizar.setEnabled(true);
            btnEliminar.setEnabled(true);
            btnDescontar.setEnabled(true);
        }// fin del if
    }// fin del metodo clickEnRegistro
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnDescontar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlTablaInventario;
    private javax.swing.JTable tblInventario;
    // End of variables declaration//GEN-END:variables
}
