
/**
 * Formulario para actualizar los antecedentes personales de un paciente
 * @author QUINCHO
 */
package presentacion;

import java.awt.Dialog;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import entidad.ExpedienteVacunas;
import entidad.ExpedientePadecimientos;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import negocio.NegocioExpedientePadecimientos;
import negocio.NegocioExpedienteVacunas;
import negocio.NegocioExpedienteMedico;
import negocio.NegocioVacuna;
import negocio.NegocioPadecimiento;


public class ContenedorAntecedentesPersonales extends javax.swing.JPanel
{
    DefaultTableModel modeloVacunas;
    DefaultTableModel modeloPadecimientosPersonales;
    ArrayList<String> idsDeVacunasAEliminar = new ArrayList<>();
    ArrayList<String> nombresDeVacunasAAgregar = new ArrayList<>();   // se guarda el tipo o nombre de la vacuna
    ArrayList<String> idsDePadecimientosAEliminar = new ArrayList<>();
    ArrayList<String> nombresDePadecimientosAAgregar = new ArrayList<>();
    String idExpedienteMedico;
    String contenidoDeAlergias;
    Dialog parent;
    
    public ContenedorAntecedentesPersonales(String idPaciente) 
    {
        initComponents();
        String idExpediente = obtenerIdExpediente(idPaciente);
        inicializarTablaVacunas(idExpediente);
        this.idExpedienteMedico = idExpediente;
        inicializarTablaPadecimientos();
        inicializarAlergias();
        inhabilitarCamposVacunas();
        inhabilitarCamposPadecimientos();
        txaAlergias.setEnabled(false);
        contenidoDeAlergias = txaAlergias.getText();
    }// fin del constructor de ContenedorAntecedentesPersonales

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPadecimientos = new javax.swing.JTable();
        btnAgregarPadecimiento = new javax.swing.JButton();
        btnEliminarPadecimiento = new javax.swing.JButton();
        btnIngresarPadecimiento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTratamiento = new javax.swing.JTextField();
        txtMedicamento = new javax.swing.JTextField();
        txtPadecimiento = new javax.swing.JTextField();
        pnlVacunas = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblVacunas = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtVacunaFechaApli = new com.toedter.calendar.JDateChooser();
        txtVacunaTipo = new javax.swing.JTextField();
        btnAgregarVacuna = new javax.swing.JButton();
        btnEliminarVacuna = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        pnlAlergias = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaAlergias = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1063, 575));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Padecimientos"));

        tblPadecimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Padecimiento", "Tratamiento", "Medicamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPadecimientos);

        btnAgregarPadecimiento.setText("Agregar");
        btnAgregarPadecimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPadecimientoActionPerformed(evt);
            }
        });

        btnEliminarPadecimiento.setText("Eliminar");
        btnEliminarPadecimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPadecimientoActionPerformed(evt);
            }
        });

        btnIngresarPadecimiento.setText("Añadir");
        btnIngresarPadecimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarPadecimientoActionPerformed(evt);
            }
        });

        jLabel1.setText("Padecimiento");

        jLabel2.setText("Tratamiento");

        jLabel3.setText("Medicamento");

        txtMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicamentoActionPerformed(evt);
            }
        });

        txtPadecimiento.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAgregarPadecimiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTratamiento, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                            .addComponent(txtMedicamento)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnIngresarPadecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEliminarPadecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(txtPadecimiento)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarPadecimiento)
                    .addComponent(btnEliminarPadecimiento))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresarPadecimiento)
                    .addComponent(jLabel1)
                    .addComponent(txtPadecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 56, Short.MAX_VALUE))
        );

        pnlVacunas.setBorder(javax.swing.BorderFactory.createTitledBorder("Vacunas"));

        tblVacunas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tipo", "Fecha de aplicación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblVacunas);

        jLabel15.setText("Tipo");

        jLabel16.setText("Fecha Aplicación");

        txtVacunaFechaApli.setDateFormatString("dd-MM-yyyy");

        btnAgregarVacuna.setText("Agregar");
        btnAgregarVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarVacunaActionPerformed(evt);
            }
        });

        btnEliminarVacuna.setText("Eliminar");
        btnEliminarVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVacunaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVacunasLayout = new javax.swing.GroupLayout(pnlVacunas);
        pnlVacunas.setLayout(pnlVacunasLayout);
        pnlVacunasLayout.setHorizontalGroup(
            pnlVacunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVacunasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVacunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                    .addGroup(pnlVacunasLayout.createSequentialGroup()
                        .addGroup(pnlVacunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVacunasLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(69, 69, 69)
                                .addComponent(txtVacunaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlVacunasLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(txtVacunaFechaApli, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlVacunasLayout.createSequentialGroup()
                                .addComponent(btnAgregarVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlVacunasLayout.setVerticalGroup(
            pnlVacunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVacunasLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlVacunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarVacuna)
                    .addComponent(btnEliminarVacuna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlVacunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVacunaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(pnlVacunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(txtVacunaFechaApli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
        );

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        pnlAlergias.setBorder(javax.swing.BorderFactory.createTitledBorder("Alergias"));

        txaAlergias.setColumns(20);
        txaAlergias.setRows(5);
        jScrollPane2.setViewportView(txaAlergias);

        javax.swing.GroupLayout pnlAlergiasLayout = new javax.swing.GroupLayout(pnlAlergias);
        pnlAlergias.setLayout(pnlAlergiasLayout);
        pnlAlergiasLayout.setHorizontalGroup(
            pnlAlergiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        pnlAlergiasLayout.setVerticalGroup(
            pnlAlergiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlAlergias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pnlVacunas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlVacunas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pnlAlergias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditar)
                            .addComponent(btnGuardar))
                        .addGap(56, 56, 56))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicamentoActionPerformed

    private void btnAgregarVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarVacunaActionPerformed
        // TODO add your handling code here:
        
        //NegocioPadecimiento objNegocioPad = new NegocioPadecimiento();
        String fila [] = new String [2];
        int idPadecimiento;   // variable donde se guardara el id del padecimiento recien agregado,
                              // retornado por el metodo obtenerId
        SimpleDateFormat formatoFecha = new SimpleDateFormat(
                txtVacunaFechaApli.getDateFormatString());
        
        if (txtVacunaTipo.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Debe ingresar una vacuna para agregar", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        
        else
        {
            try
            {
                fila[0] = txtVacunaTipo.getText();
                fila[1] = formatoFecha.format(txtVacunaFechaApli.getDate());
        
                modeloVacunas.addRow(fila);
                nombresDeVacunasAAgregar.add(fila[0]);  // se agrega a la lista
        
                limpiarCamposVacunas();   // se limpian los campos de texto
            }// fin del try
            catch (NullPointerException npe)
            {
                fila[1] = null;
                
                modeloVacunas.addRow(fila);
                nombresDeVacunasAAgregar.add(fila[0]);  // se agrega a la lista
            }// fin del catch
            
        }// fin del else
    }//GEN-LAST:event_btnAgregarVacunaActionPerformed

    private void btnEliminarVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVacunaActionPerformed
        // TODO add your handling code here:
        
        int filaSeleccionada = tblVacunas.getSelectedRow();
        
        if (filaSeleccionada == -1)
            JOptionPane.showMessageDialog(null, "Debe seleccionar una vacuna para eliminar", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        
        else
        {
            int confirmacion = JOptionPane.showConfirmDialog(null, 
                    "Está seguro de eliminar la vacuna");
            
            if (confirmacion == JOptionPane.YES_OPTION)
            {                
                try 
                {
                    idsDeVacunasAEliminar.add(
                            tblVacunas.getValueAt(filaSeleccionada, 2).toString());
                
                    modeloVacunas.removeRow(filaSeleccionada);
                }// fin del try
                catch (NullPointerException npe)
                {
                    nombresDeVacunasAAgregar.remove(
                            tblVacunas.getValueAt(filaSeleccionada, 0).toString());
                    
                    modeloVacunas.removeRow(filaSeleccionada);
                }// fin del catch
                
            }// fin del if
        }// fin del else
    }//GEN-LAST:event_btnEliminarVacunaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        //ingresarVacunas();
        //eliminarVacunas();
        //actualizarAlergias();
        //eliminarPadecimientos();
        //ingresarPadecimientosPersonales();
        guardarCambios();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        habilitarCamposVacunas();
        habilitarCamposPadecimientos();
        txaAlergias.setEnabled(true);
    }//GEN-LAST:event_btnEditarActionPerformed
    private void btnEliminarPadecimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPadecimientoActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tblPadecimientos.getSelectedRow();
        
        if (filaSeleccionada == -1)
            JOptionPane.showMessageDialog(null, "Debe seleccionar un padecimiento  para eliminar", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        
        else
        {
            int confirmacion = JOptionPane.showConfirmDialog(null, 
                    "Está seguro de eliminar el padecimiento");
            
            if (confirmacion == JOptionPane.YES_OPTION)
            {                
                try 
                {
                    idsDePadecimientosAEliminar.add(
                            tblPadecimientos.getValueAt(filaSeleccionada, 3).toString());
                
                    modeloPadecimientosPersonales.removeRow(filaSeleccionada);
                }// fin del try
                catch (NullPointerException npe)
                {
                    System.out.println(nombresDePadecimientosAAgregar.size());
                    nombresDePadecimientosAAgregar.remove(
                            tblPadecimientos.getValueAt(filaSeleccionada, 0).toString());
                    
                    modeloPadecimientosPersonales.removeRow(filaSeleccionada);
                    System.out.println(nombresDePadecimientosAAgregar.size());
                }// fin del catch
                
            }// fin del if
        }// fin del else
    }//GEN-LAST:event_btnEliminarPadecimientoActionPerformed

    private void btnAgregarPadecimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPadecimientoActionPerformed
        // TODO add your handling code here:
        
        String fila [] = new String [3];
        int idPadecimiento;   // variable donde se guardara el id del padecimiento recien agregado,
                              // retornado por el metodo obtenerId
        
        if (txtPadecimiento.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Debe ingresar un padecimiento para agregar", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        
        else
        {
            fila[0] = txtPadecimiento.getText();
            fila[1] = txtTratamiento.getText();
            fila[2] = txtMedicamento.getText();
        
            modeloPadecimientosPersonales.addRow(fila);
            nombresDePadecimientosAAgregar.add(fila[0]);  // se agrega a la lista
        
            limpiarCamposPadecimientos();   // se limpian los campos de texto
        }// fin del else
    }//GEN-LAST:event_btnAgregarPadecimientoActionPerformed

    private void btnIngresarPadecimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarPadecimientoActionPerformed
        // TODO add your handling code here:
        
        CatalogoPadecimientos padecimientos = new CatalogoPadecimientos(parent, true);
        padecimientos.setVisible(true);
        
        txtPadecimiento.setText(padecimientos.arreglo[0]);
    }//GEN-LAST:event_btnIngresarPadecimientoActionPerformed
    
    private void inicializarTablaVacunas(String idExpedienteMedico)
    {
        modeloVacunas = new DefaultTableModel()   //  modelo instanciado
                {
                    @Override // ihabilitamos la tabla para no permitir la edicion de sus columnas
                    public boolean isCellEditable(int rowIndex, int columnIndex)
                    {
                        return false;
                    }// fin del metodo isCellEditable
                };   // modelo de la tabla de padecimientos
        
        modeloVacunas.addColumn("Tipo");  // agregamos las cabeceras de columnas
        modeloVacunas.addColumn("Fecha de aplicación");    // al modelo
        modeloVacunas.addColumn("Id");
        
        NegocioExpedienteVacunas objNegocioExpVacu = new NegocioExpedienteVacunas();
        String fila [] = new String [3];
        ResultSet rs;
        
        try
        {
            rs = objNegocioExpVacu.listarVacunas(idExpedienteMedico);
            
            while (rs.next())
            {
                fila[0] = rs.getString(1);
                fila[1] = rs.getString(2);
                fila[2] = rs.getString(3);                
                
                modeloVacunas.addRow(fila);  // agregamos una fila al modelo por el arreglo
            }// fin del while
            
            tblVacunas.setModel(modeloVacunas);
            
            // Escondemos la columna de Id
            tblVacunas.getColumnModel().getColumn(2).setMaxWidth(0);
            tblVacunas.getColumnModel().getColumn(2).setMinWidth(0);
            tblVacunas.getColumnModel().getColumn(2).setPreferredWidth(0);
            
            
        }// fin del try
        catch(SQLException sqle)
        {
            System.out.println(sqle.getErrorCode() + sqle.getMessage());
        }// fin del catch
        
    }// fin del metodo inicilizarTablaVacunas

    // El siguiente metodo elimina las vacunas seleccionadas de la BD
    private void eliminarVacunas()
    {
        NegocioExpedienteVacunas objNegocioExpVac = new NegocioExpedienteVacunas();
        
        for (int i = 0; i < idsDeVacunasAEliminar.size(); i++)
        {
            objNegocioExpVac.eliminarVacuna(idsDeVacunasAEliminar.get(i));
                    
        }// fin del for
        
    }// fin del metodo eliminarPadecimientosFamiliares
    
    // El siguiente metodo ingresa vacunas asociadas al paciente en la base de datos
    private void ingresarVacunas()
    {
        NegocioVacuna objNegocioVacuna = new NegocioVacuna();
        NegocioExpedienteVacunas objNegocioExpVac = new NegocioExpedienteVacunas();
        ExpedienteVacunas objExpVac [] = new ExpedienteVacunas[nombresDeVacunasAAgregar.size()];
        
        String idVacunas [] = new String [nombresDeVacunasAAgregar.size()];  // se guardaran los ids de cada
                                                                    // vacunas para despues insertar
                                                                    
        for (int i = 0; i < nombresDeVacunasAAgregar.size(); i++)
            objNegocioVacuna.consultarInsertarVacuna(nombresDeVacunasAAgregar.get(i));
        
        for (int i = 0; i < idVacunas.length; i++)
            idVacunas[i] = objNegocioVacuna.obtenerIdVacuna(nombresDeVacunasAAgregar.get(i));
        
        // Extraemos el indice de la tabla desde donde se agregaron nuevos padecimientos
        int indice = tblVacunas.getRowCount() - nombresDeVacunasAAgregar.size();
        
        for (int i = 0; i < objExpVac.length; i++)
        {
            objExpVac[i] = new ExpedienteVacunas();
            
            // se ingresa el padecimiento seleccionado del catalogo de padecimientos (CatalogoPadecimientos.java)
            objExpVac[i].setIdVacuna(Integer.parseInt(idVacunas[i]));
            
            objExpVac[i].setIdExpediente(Integer.parseInt(idExpedienteMedico));
            
            if (tblVacunas.getValueAt(i, 1) != null)
                objExpVac[i].setFecha(getFechaVacuna(tblVacunas.getValueAt(indice, 1).toString()));
            
            else
                objExpVac[i].setFecha("0000-00-00");
            
            // insertamos en la base de datos
            objNegocioExpVac.insertarExpedienteVacunas(objExpVac[i]);
            
            indice++;
        } // fin del for
                
    }// fin del metodo ingresarVacunas
    
    // El siguiente metodo obtiene el id del expediente medico a partir de id del paciente
    private String obtenerIdExpediente(String idPaciente)
    {
        NegocioExpedienteMedico objNegocioExpMed = new NegocioExpedienteMedico();        
        return objNegocioExpMed.obtenerIdExpedienteMedico(idPaciente);
    }// fin del metodo obtenerIdExpediente
    
    private String getFechaVacuna(String fecha)
    {
        String fechaVacuna = "";
        SimpleDateFormat formatoTexto = new SimpleDateFormat("dd-MM-yyyy");
        Date fechaNueva = null;
        
        try 
        {
            fechaNueva = formatoTexto.parse(fecha);
            formatoTexto = null;
            formatoTexto = new SimpleDateFormat("yyyy-MM-dd");
            fechaVacuna = formatoTexto.format(fechaNueva);
        }// fin del try 
        catch (ParseException ex) 
        {
            Logger.getLogger(ExpedienteNuevo.class.getName()).log(Level.SEVERE, null, ex);
        }// fin del catch
        
        return fechaVacuna;
    }
    
    // Limpia los campos en el formulario de vacunas
    private void limpiarCamposVacunas()
    {
        txtVacunaTipo.setText("");
        txtVacunaFechaApli.setDate(null);
    }// fin del metodo limpiarCamposVacuna
    
    
    private void inhabilitarCamposVacunas()
    {
        txtVacunaTipo.setEnabled(false);
        txtVacunaFechaApli.setEnabled(false);
        btnAgregarVacuna.setEnabled(false);
        btnEliminarVacuna.setEnabled(false);
    }// fin del metodo inhabilitarCamposVacunas
    
    private void habilitarCamposVacunas()
    {
        txtVacunaTipo.setEnabled(true);
        txtVacunaFechaApli.setEnabled(true);
        btnAgregarVacuna.setEnabled(true);
        btnEliminarVacuna.setEnabled(true);
    }// fin del metodo habilitarCamposVacunas
    
    
    // DE AQUI PARA ABAJO COMIENZAN TODOS LOS METODOS QUE TIENEN QUE VER CON LA PARTE ALERGIAS
    private void inicializarAlergias()
    {
        NegocioExpedienteMedico objNegocioExpMed = new NegocioExpedienteMedico();
        ResultSet rs;
        
        try
        {
            rs = objNegocioExpMed.obtenerAlergias(idExpedienteMedico);
            
            if (rs.next())
                txaAlergias.setText(rs.getString("alergias"));
        }// fin del try
        catch (SQLException sqle)
        {
            System.out.println(sqle.getErrorCode() + sqle.getMessage());
        }// fin del catch
        
    }// fin del metodo inicializarAlergias
    
    // El siguiente metodo metodo actualiza las alergias pertenecientes a un paciente en la BD
    private void actualizarAlergias()
    {
        NegocioExpedienteMedico objNegocioExpMed = new NegocioExpedienteMedico();
        objNegocioExpMed.actualizarAlergias(idExpedienteMedico, txaAlergias.getText());
    }// fin del metodo actualizarAlergias
    
    
    // DE AQUI PARA ABAJ0 COMIENZAN TODOS LOS METODOS QUE TIENE QUE VER CON LOS PADECIMIENTOS PERSONALES
    private void inicializarTablaPadecimientos()
    {
        modeloPadecimientosPersonales = new DefaultTableModel()   //  modelo instanciado
                {
                    @Override // ihabilitamos la tabla para no permitir la edicion de sus columnas
                    public boolean isCellEditable(int rowIndex, int columnIndex)
                    {
                        return false;
                    }// fin del metodo isCellEditable
                };   // modelo de la tabla de padecimientos
        
        modeloPadecimientosPersonales.addColumn("Padecimiento");  // agregamos las cabeceras de columnas
        modeloPadecimientosPersonales.addColumn("Trtamiento");    // al modelo
        modeloPadecimientosPersonales.addColumn("Medicamento");
        modeloPadecimientosPersonales.addColumn("Id");
        
        NegocioExpedientePadecimientos objNegocioExpPad = new NegocioExpedientePadecimientos();
        String fila [] = new String [4];
        ResultSet rs;
        
        try
        {
            rs = objNegocioExpPad.listarPadecimientosPersonales(idExpedienteMedico);
            
            while (rs.next())
            {
                fila[0] = rs.getString(1);
                fila[1] = rs.getString(2);
                fila[2] = rs.getString(3);     
                fila[3] = rs.getString(4);
                
                modeloPadecimientosPersonales.addRow(fila);  // agregamos una fila al modelo por el arreglo
            }// fin del while
            
            tblPadecimientos.setModel(modeloPadecimientosPersonales);
            
            // Escondemos la columna de Id
            tblPadecimientos.getColumnModel().getColumn(3).setMaxWidth(0);
            tblPadecimientos.getColumnModel().getColumn(3).setMinWidth(0);
            tblPadecimientos.getColumnModel().getColumn(3).setPreferredWidth(0);
        }// fin del try
        catch (SQLException sqle)
        {
            System.out.println(sqle.getErrorCode() + sqle.getMessage());
        }// fin del catch
    }// fin del metodo eliminarPadecimientosFamiliares
    
    // El siguiente metodo elimina los padecimientos seleccionados en la BD
    private void eliminarPadecimientos()
    {
        NegocioExpedientePadecimientos objNegocioExpPad = new NegocioExpedientePadecimientos();
        
        for (int i = 0; i < idsDePadecimientosAEliminar.size(); i++)
            objNegocioExpPad.eliminarPadecimientoPersonal(idsDePadecimientosAEliminar.get(i));
    }// fin del metodo inicializarTablaPadecimientos
    
    // El siguiente metodo ingresa los antecedentes seleccionado de la BD
    private void ingresarPadecimientosPersonales()
    {
        NegocioExpedientePadecimientos objNegocioExpPad = 
                new NegocioExpedientePadecimientos();
        NegocioPadecimiento objNegocioPad = new NegocioPadecimiento();
        int idsPadecimientos [] = new int [nombresDePadecimientosAAgregar.size()];
        ExpedientePadecimientos objExpPad [] 
                = new ExpedientePadecimientos [idsPadecimientos.length];
        
        for (int i = 0; i < idsPadecimientos.length; i++)  // obtemos los ids de los padecimientos enlistados
            idsPadecimientos[i] = objNegocioPad.obtenerId(nombresDePadecimientosAAgregar.get(i));
        
        // Extraemos el indice de la tabla desde donde se agregaron nuevos padecimientos
        int indice = tblPadecimientos.getRowCount() - nombresDePadecimientosAAgregar.size();
        
        for (int i = 0; i < objExpPad.length; i++)
        {
            objExpPad[i] = new ExpedientePadecimientos();
            
            // se ingresa el padecimiento seleccionado del catalogo de padecimientos (CatalogoPadecimientos.java)
            objExpPad[i].setIdPadecimiento(idsPadecimientos[i]);
            
            objExpPad[i].setIdExpediente(Integer.parseInt(idExpedienteMedico));   // se ingresan los    
            objExpPad[i].setTratamiento(tblPadecimientos.getValueAt(indice, 1).toString());  // restantes
            objExpPad[i].setMedicamento(tblPadecimientos.getValueAt(indice, 2).toString()); // atributos
            
            // insertamos en la base de datos
            objNegocioExpPad.insertarExpedientePadecimientos(objExpPad[i]);
            
            indice++;
        } // fin del for
    }// fin del metodo ingresarPadecimientosFamiliares
    
    // limpia los campos en el formulario de padecimientos
    private void limpiarCamposPadecimientos()
    {
        txtPadecimiento.setText("");
        txtTratamiento.setText("");
        txtMedicamento.setText("");
    }// fin del metodo limpiarCamposPadecimientos
    
    private void inhabilitarCamposPadecimientos()
    {
        txtPadecimiento.setEnabled(false);
        txtTratamiento.setEnabled(false);
        txtMedicamento.setEnabled(false);
        btnAgregarPadecimiento.setEnabled(false);
        btnEliminarPadecimiento.setEnabled(false);
        btnIngresarPadecimiento.setEnabled(false);
    }// fin del metodo inhabilitarCamposPadecimientos
    
    private void habilitarCamposPadecimientos()
    {
        txtPadecimiento.setEnabled(true);
        txtTratamiento.setEnabled(true);
        txtMedicamento.setEnabled(true);
        btnAgregarPadecimiento.setEnabled(true);
        btnEliminarPadecimiento.setEnabled(true);
        btnIngresarPadecimiento.setEnabled(true);
    }// fin del metodo inhabilitarCamposPadecimientos
    
    
    // EL SIGUIENTE METODO GUARDA LOS CAMBIOS SI LOS HUBIESE EN ESTE FORMULARIO
    private void guardarCambios()
    {
        boolean cambios = false;   // variable para determinar si se realizaron cambios
        
        if (! idsDePadecimientosAEliminar.isEmpty())
        {
            eliminarPadecimientos();
            cambios = true;
        }// fin del if
        
        if (! nombresDePadecimientosAAgregar.isEmpty())
        {
            ingresarPadecimientosPersonales();
            cambios = true;
        }// fin del if
        
        if (! idsDeVacunasAEliminar.isEmpty())
        {
            eliminarVacunas();
            cambios = true;
        }// fin del if 
        
        if (! nombresDeVacunasAAgregar.isEmpty())
        {
            ingresarVacunas();
            cambios = true;
        }// fin del if 
        
        if (! contenidoDeAlergias.equals(txaAlergias.getText()))  // compara si se realizaron cambios en alergias
        {
            actualizarAlergias();
            cambios = true;
        }// fin del if
        
        if (cambios == true)
            JOptionPane.showMessageDialog(null, "Los cambios en antecedenes personales se han guardado "
                    + "con éxito", "Información", JOptionPane.INFORMATION_MESSAGE);
        
        else
            JOptionPane.showMessageDialog(null, "No se realizaron cambios", "Información", 
                    JOptionPane.INFORMATION_MESSAGE);
    }// fin del metodo guardarCambios
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPadecimiento;
    private javax.swing.JButton btnAgregarVacuna;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminarPadecimiento;
    private javax.swing.JButton btnEliminarVacuna;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnIngresarPadecimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel pnlAlergias;
    private javax.swing.JPanel pnlVacunas;
    private javax.swing.JTable tblPadecimientos;
    private javax.swing.JTable tblVacunas;
    private javax.swing.JTextArea txaAlergias;
    private javax.swing.JTextField txtMedicamento;
    private javax.swing.JTextField txtPadecimiento;
    private javax.swing.JTextField txtTratamiento;
    private com.toedter.calendar.JDateChooser txtVacunaFechaApli;
    private javax.swing.JTextField txtVacunaTipo;
    // End of variables declaration//GEN-END:variables
}// fin de la clase ContenedorAntecedentesPersonales
