
package presentacion;

/**
 *
 * @author QUINCHO
 */

import entidad.Paciente;
import entidad.enums.SexoEnum;
import entidad.enums.TipoEnum;
import negocio.NegocioPaciente;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


public class VerExpediente extends javax.swing.JDialog 
{
    private String idPaciente;  // representa el id del paciente en la base de datos
    private String idTelefono; // representa el id del telefono ya que se decidio agregar los telefono en una tabla distinta en la base de datos
    
    public VerExpediente(java.awt.Frame parent, boolean modal, String cedulaPaciente, String id)
    {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(parent);
        cargarDatosPaciente(cedulaPaciente);
        deshabilitarComponentes();
        ocultarEtiquetas();
        
        this.idPaciente = id;
    }// fin del constructor de VerExpediente

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelDatosPersonales = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textApellido2 = new javax.swing.JTextField();
        textIdentificacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textApellido1 = new javax.swing.JTextField();
        textNacionalidad = new javax.swing.JTextField();
        textFechaNac = new datechooser.beans.DateChooserCombo();
        jLabel7 = new javax.swing.JLabel();
        textTelefono = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        cbSexo = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox();
        lblValidaTipo = new javax.swing.JLabel();
        lblValidaNombre = new javax.swing.JLabel();
        lblValidaIndentificacion = new javax.swing.JLabel();
        lblValidaNacionalidad = new javax.swing.JLabel();
        lblValidaApellido1 = new javax.swing.JLabel();
        lblValidaEmail = new javax.swing.JLabel();
        lblValidaSexo = new javax.swing.JLabel();
        lblValidaSegundoApellido = new javax.swing.JLabel();
        lblValidaTelefono = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDireccionFamiliar = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textDireccionLectiva = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/icons/profile128.png"))); // NOI18N

        jLabel5.setText("Email");

        jLabel1.setText("Nombre");

        jLabel6.setText("Fecha Nac");

        jLabel8.setText("Sexo");

        jLabel2.setText("P. Apellido");

        jLabel4.setText("Cédula");

        jLabel3.setText("S. Apellido");

        textFechaNac.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    textFechaNac.setCurrentNavigateIndex(0);
    textFechaNac.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);
    textFechaNac.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
        public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
            textFechaNacOnSelectionChange(evt);
        }
    });

    jLabel7.setText("Nacionalidad");

    cbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Masculino", "Femenino" }));

    jLabel22.setText("Teléfono");

    jLabel20.setText("Tipo");

    cbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Administrativo", "Estudiante", "Docente" }));

    lblValidaTipo.setText("*");

    lblValidaNombre.setText("*");

    lblValidaIndentificacion.setText("*");

    lblValidaNacionalidad.setText("*");

    lblValidaApellido1.setText("*");

    lblValidaEmail.setText("*");

    lblValidaSexo.setText("*");

    lblValidaSegundoApellido.setText("*");

    lblValidaTelefono.setText("*");

    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel8Layout.createSequentialGroup()
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1)
                .addComponent(jLabel4)
                .addComponent(jLabel7)
                .addComponent(jLabel20))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addComponent(textIdentificacion)
                        .addComponent(textNacionalidad))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblValidaNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblValidaIndentificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 19, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblValidaNacionalidad)
                            .addGap(17, 17, 17)))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel5)
                        .addComponent(jLabel8))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textApellido1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addComponent(textEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addComponent(cbSexo, 0, 171, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblValidaApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValidaEmail, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(lblValidaSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 21, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6)
                        .addComponent(jLabel22))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)))
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblValidaTipo)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(lblValidaSegundoApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblValidaTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    jPanel8Layout.setVerticalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
            .addContainerGap(19, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel20)
                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblValidaTipo))
            .addGap(18, 18, 18)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1)
                .addComponent(jLabel2)
                .addComponent(textApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3)
                .addComponent(textApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblValidaNombre)
                .addComponent(lblValidaApellido1)
                .addComponent(lblValidaSegundoApellido))
            .addGap(18, 18, 18)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(lblValidaIndentificacion))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(lblValidaEmail))
                .addComponent(textFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValidaTelefono))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(lblValidaNacionalidad))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(lblValidaSexo)))
            .addGap(27, 27, 27))
    );

    jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Direcciones"));

    textDireccionFamiliar.setColumns(20);
    textDireccionFamiliar.setRows(5);
    jScrollPane1.setViewportView(textDireccionFamiliar);

    jLabel10.setText("En tiempo lectivo");

    textDireccionLectiva.setColumns(20);
    textDireccionLectiva.setRows(5);
    jScrollPane2.setViewportView(textDireccionLectiva);

    jLabel9.setText("Familiar");

    javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
    jPanel9.setLayout(jPanel9Layout);
    jPanel9Layout.setHorizontalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel9Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1)
                .addComponent(jScrollPane2)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10))
                    .addGap(0, 930, Short.MAX_VALUE)))
            .addContainerGap())
    );
    jPanel9Layout.setVerticalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel9Layout.createSequentialGroup()
            .addComponent(jLabel9)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel10)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    btnGuardar.setText("Guardar");
    btnGuardar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnGuardarActionPerformed(evt);
        }
    });

    btnEditar.setText("Editar");
    btnEditar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnEditarActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout panelDatosPersonalesLayout = new javax.swing.GroupLayout(panelDatosPersonales);
    panelDatosPersonales.setLayout(panelDatosPersonalesLayout);
    panelDatosPersonalesLayout.setHorizontalGroup(
        panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelDatosPersonalesLayout.createSequentialGroup()
            .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosPersonalesLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosPersonalesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosPersonalesLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(17, 17, 17)))
            .addContainerGap())
    );
    panelDatosPersonalesLayout.setVerticalGroup(
        panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelDatosPersonalesLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel12))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(27, 27, 27)
            .addGroup(panelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnEditar)
                .addComponent(btnGuardar))
            .addContainerGap(56, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("DatosPersonales", panelDatosPersonales);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 1063, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 575, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("tab2", jPanel2);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 1063, Short.MAX_VALUE)
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 575, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("tab3", jPanel3);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTabbedPane1)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTabbedPane1)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFechaNacOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_textFechaNacOnSelectionChange

    }//GEN-LAST:event_textFechaNacOnSelectionChange

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        habilitarComponentes();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (!validarCampos())
            JOptionPane.showMessageDialog(null, "Unos o más campos son incorrectos. Revisar campos con '*'", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        
        else
        {
            actualizarDatosPaciente();
            
            JOptionPane.showMessageDialog(null, "Los datos del paciente se han actualizado exitosamente", 
                    "Información", JOptionPane.INFORMATION_MESSAGE);
            
            deshabilitarComponentes();
        }// fin del else
    }//GEN-LAST:event_btnGuardarActionPerformed

    // metodo que carga los datos del paciente en este formulario
    private void cargarDatosPaciente(String cedulaPaciente)
    {
        Paciente objPaciente = new Paciente();
        NegocioPaciente objNegocioPaciente = new NegocioPaciente();
        
        ResultSet rs;
        
        try
        {
            rs = objNegocioPaciente.obtenerDatosPaciente(cedulaPaciente);
            
            if (rs.next())
            {
                // damos los valores obtenidos de la base de datos al objeto Paciente(objPaciente)
                objPaciente.setNombrePaciente(rs.getString("nombrePaciente"));
                objPaciente.setApellido1(rs.getString("apellido1Paciente"));
                objPaciente.setApellido2(rs.getString("apellido2Paciente"));
                objPaciente.setIdentificacion(rs.getString("cedulaPaciente"));
                objPaciente.setTelefono(rs.getString("numeroTelefono"));
                objPaciente.setEmail(rs.getString("email"));
                objPaciente.setFechaNacimiento(rs.getDate("fechaNacimientoPaciente").toString());
                objPaciente.setNacionalidad(rs.getString("nacionalidadPaciente"));
                objPaciente.setDireccion1(rs.getString("direccion1"));
                objPaciente.setDireccion2(rs.getString("direccion2"));
                
                idTelefono = rs.getString(9);   // recuperamos el idTelefono(llave foranea) del paciente
                
                // obtenemos los enumerados para el sexo y el tipo del Paciente
                if (rs.getInt("sexo") == 1)
                    objPaciente.setSexo(SexoEnum.MASCULINO);
                
                else
                    objPaciente.setSexo(SexoEnum.FEMENINO);
                
                if (rs.getInt("tipo") == 1)
                    objPaciente.setTipo(TipoEnum.ADMINISTRATIVO);
                
                else
                {
                    if (rs.getInt("tipo") == 2)
                        objPaciente.setTipo(TipoEnum.ESTUDIANTE);
                    
                    else
                        objPaciente.setTipo(TipoEnum.DOCENTE);
                }// fin del else
            }// fin del if
            
            // Se cargan los componentes con el objeto Paciente(objPaciente)
            textNombre.setText(objPaciente.getNombrePaciente());
            textApellido1.setText(objPaciente.getApellido1());
            textApellido2.setText(objPaciente.getApellido2());
            textIdentificacion.setText(objPaciente.getIdentificacion());
            textTelefono.setText(objPaciente.getTelefono());
            textEmail.setText(objPaciente.getEmail());
            textFechaNac.setText(convertirFecha(objPaciente.getFechaNacimiento()));
            textNacionalidad.setText(objPaciente.getNacionalidad());
            textDireccionFamiliar.setText(objPaciente.getDireccion1());
            textDireccionLectiva.setText(objPaciente.getDireccion2());
            cbSexo.setSelectedIndex(objPaciente.getSexo().getSexo());
            cbTipo.setSelectedIndex(objPaciente.getTipo().obtenerTipoNumero());
            //System.out.println(convertirFecha(objPaciente.getFechaNacimiento()));
        }// fin del try
        catch(SQLException sqle)
        {
            JOptionPane.showMessageDialog(null, "Error al conectar con la base de datos", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }// fin del catch
    }// fin del metodo cargarDatosPaciente
    
    /**
     * Metodo para convertir en la fecha en formato mm/dd/yy
     * @param fecha
     * @return 
     */
    private String convertirFecha(String fecha)
    {
        String fechaSalida = "";   // String retornado por este metodo
        SimpleDateFormat formatoDelTexto = new SimpleDateFormat("yyyy-MM-dd");
        Date fechaNueva = null;
        DateFormat formatoFecha = DateFormat.getDateInstance(DateFormat.SHORT);
        
        try
        {
            fechaNueva = formatoDelTexto.parse(fecha);
            fechaSalida = formatoFecha.format(fechaNueva);
        }// fin del try
        catch(ParseException pe)
        {
            pe.printStackTrace();
        }// fin del catch
        
        return fechaSalida;
    }// fin del metodo convertirFecha
    
    // El siguiente metodo actualiza los datos de un paciente, en la base de datos
    public void actualizarDatosPaciente()
    {
        Paciente objetoPaciente = new Paciente();  // objeto Paciente a pasar por parametro
        NegocioPaciente objetoNegocioPaciente = new NegocioPaciente();
        
        // Se establecen las propiedades de objetoPaciente
        objetoPaciente.setNombrePaciente(textNombre.getText());
        objetoPaciente.setApellido1(textApellido1.getText());
        objetoPaciente.setApellido2(textApellido2.getText());
        objetoPaciente.setIdentificacion(textIdentificacion.getText());
        objetoPaciente.setTelefono(textTelefono.getText());
        objetoPaciente.setEmail(textEmail.getText());
        objetoPaciente.setFechaNacimiento(convertirFechaIngresar());
        objetoPaciente.setNacionalidad(textNacionalidad.getText());
        objetoPaciente.setDireccion1(textDireccionFamiliar.getText());
        objetoPaciente.setDireccion2(textDireccionLectiva.getText());
        
        switch(cbSexo.getSelectedIndex())  // switch para establecer el enumerado SexoEnum
        {
            case 1: objetoPaciente.setSexo(SexoEnum.MASCULINO);
                break;
            case 2: objetoPaciente.setSexo(SexoEnum.FEMENINO);
                break;
        }// fin del switch
               
        switch(cbTipo.getSelectedIndex())   // switch para establecer el enumerado TipoEnum
        {
            case 1: objetoPaciente.setTipo(TipoEnum.ADMINISTRATIVO);
                break;    
            case 2: objetoPaciente.setTipo(TipoEnum.ESTUDIANTE);
                break;
            case 3: objetoPaciente.setTipo(TipoEnum.DOCENTE);
                break;
        }// fin del switch
        
        // se actualizan los datos
        objetoNegocioPaciente.actualizarDatosPaciente(objetoPaciente, idPaciente, idTelefono);
    }// fin del metodo actualizarDatosPaciente
    
    // El siguiente metodo convierte la fecha de formato mm/dd/yy a yyyy/mm/dd
    private String convertirFechaIngresar()
    {
        String fechaNac = "";
        final int year = textFechaNac.getCurrent().get(Calendar.YEAR);
        final int day = textFechaNac.getCurrent().get(Calendar.DAY_OF_MONTH);
        final int month = textFechaNac.getCurrent().get(Calendar.MONTH) + 1;
        fechaNac = year+"-"+month+"-"+day;
        return fechaNac;
    }// fin del metodo convertirFechaIngresar
    
    // El siguiente metodo deshabilita los componenetes graficos del formulario
    private void deshabilitarComponentes()
    {
        textNombre.setEnabled(false);
        textApellido1.setEnabled(false);
        textApellido2.setEnabled(false);
        textIdentificacion.setEnabled(false);
        textTelefono.setEnabled(false);
        textEmail.setEnabled(false);
        textFechaNac.setEnabled(false);
        textNacionalidad.setEnabled(false);
        textDireccionFamiliar.setEnabled(false);
        textDireccionLectiva.setEnabled(false);
        cbSexo.setEnabled(false);
        cbTipo.setEnabled(false);
    }// fin del metodo deshabilitarComponentes
    
    private void habilitarComponentes()
    {
        textNombre.setEnabled(true);
        textApellido1.setEnabled(true);
        textApellido2.setEnabled(true);
        textIdentificacion.setEnabled(true);
        textTelefono.setEnabled(true);
        textEmail.setEnabled(true);
        textFechaNac.setEnabled(true);
        textNacionalidad.setEnabled(true);
        textDireccionFamiliar.setEnabled(true);
        textDireccionLectiva.setEnabled(true);
        cbSexo.setEnabled(true);
        cbTipo.setEnabled(true);
    }// fin del metodo habilitarComponentes
    
    // El siguiente metodo oculta todos las etiquetas(JLabel) que son usadas para validar los campos
    private void ocultarEtiquetas()
    {
        lblValidaNombre.setVisible(false);
        lblValidaApellido1.setVisible(false);
        lblValidaEmail.setVisible(false);
        lblValidaIndentificacion.setVisible(false);
        lblValidaNacionalidad.setVisible(false);
        lblValidaSegundoApellido.setVisible(false);
        lblValidaSexo.setVisible(false);
        lblValidaTelefono.setVisible(false);
        lblValidaTipo.setVisible(false);    
    }// fin del metodo ocultarEtiquetas
    
    private boolean validarCampos()
    {
        boolean validado = true;  // inicializada en true para indicar que todos los campos estan correctamente
        
        JTextField camposDeTexto [] = {textNombre, textApellido1, textApellido2,
                                       textNacionalidad};  // arreglo que contiene los JTextField del Formulario que no deben quedar vacios
                                                        
        // arreglo que contiene los JLabel que representa un campo si esta vacio
        JLabel etiquetasDeVacios [] = {lblValidaNombre, lblValidaApellido1, lblValidaSegundoApellido,
                                       lblValidaNacionalidad};
        
        for (int i = 0; i < camposDeTexto.length; i++)   // Este bloque for verifica que ningun campo en el
        {                                                // arreglo quede vacio; de ser asi, pone un asterisco   
            if (camposDeTexto[i].getText().isEmpty())    // a lado del campo vacio, para indicar que ese campo
            {                                            // requiere ser llenado
                etiquetasDeVacios[i].setVisible(true);
                validado = false;
            }// fin del if
            else
                etiquetasDeVacios[i].setVisible(false);
        }// fin del for
        
        // validamos el combobox de tipo
        if (cbTipo.getSelectedIndex() == 0)
        {
            lblValidaTipo.setVisible(true);
            validado = false;
        }// fin del if
        
        else
            lblValidaTipo.setVisible(false);
        
        // validamos el combobox de sexo
        if (cbSexo.getSelectedIndex() == 0)
        {
            lblValidaSexo.setVisible(true);
            validado = false;
        }// fin del if
        
        else
            lblValidaSexo.setVisible(false);
        
        if (textIdentificacion.getText().matches(".*[0-9].*"))
            lblValidaIndentificacion.setVisible(false);
        
        else
        {
            lblValidaIndentificacion.setVisible(true);
            validado = false;
        }// fin del else
        
        if (textEmail.getText().matches("([a-zA-Z0-9]+([-_.]*)?([a-zA-Z0-9]+)?\\@[a-zA-Z]+\\.[a-zA-Z]+)?"))
            lblValidaEmail.setVisible(false);
        
        else
        {
            lblValidaEmail.setVisible(true);
            validado = false;
        }// fin del else
        
        if (textTelefono.getText().matches("(.*[0-9].*)?"))
            lblValidaTelefono.setVisible(false);
        
        else
        {
            lblValidaTelefono.setVisible(true);
            validado = false;
        }// fin del else
        
        return validado;
    }// fin del metodo validar campos
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VerExpediente dialog = new VerExpediente(new javax.swing.JFrame(), true, new String(), new String());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cbSexo;
    private javax.swing.JComboBox cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblValidaApellido1;
    private javax.swing.JLabel lblValidaEmail;
    private javax.swing.JLabel lblValidaIndentificacion;
    private javax.swing.JLabel lblValidaNacionalidad;
    private javax.swing.JLabel lblValidaNombre;
    private javax.swing.JLabel lblValidaSegundoApellido;
    private javax.swing.JLabel lblValidaSexo;
    private javax.swing.JLabel lblValidaTelefono;
    private javax.swing.JLabel lblValidaTipo;
    private javax.swing.JPanel panelDatosPersonales;
    private javax.swing.JTextField textApellido1;
    private javax.swing.JTextField textApellido2;
    private javax.swing.JTextArea textDireccionFamiliar;
    private javax.swing.JTextArea textDireccionLectiva;
    private javax.swing.JTextField textEmail;
    private datechooser.beans.DateChooserCombo textFechaNac;
    private javax.swing.JTextField textIdentificacion;
    private javax.swing.JTextField textNacionalidad;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textTelefono;
    // End of variables declaration//GEN-END:variables
}
